import { LanguageOption } from './config';

// define list of LanguageOption[]
const languageOptions: LanguageOption[] = [
  {
    code: 'en',
    localeCode: 'en',
    label: 'English',
    default: true,
    textDirection: 'ltr',
    iso3LetterCode: 'eng',
    cmsLocale: 'en-GB', // what locale code to use when fetching data from the cms endpoints
    vocabularyLocale: 'en', // what locale code to use when fetching data from the vocabulary endpoints
    gbifOrgLocalePrefix: '',
    mapTileLocale: 'en',
  },
  {
    code: 'nonsense',
    localeCode: 'en-ZZ',
    label: 'Test',
    default: false,
    textDirection: 'ltr',
    cmsLocale: 'es',
    reactIntlLocale: 'ar-SA',
    gbifOrgLocalePrefix: '',
    grSciCollLocalePrefix: '',
  },
  {
    code: 'danglish', // TODO, developer english.  while developing it is convinent to have developer english when text change so taht we can see changes immeadiately
    localeCode: 'en-DK',
    label: 'Danglish',
    default: false,
    textDirection: 'ltr',
    gbifOrgLocalePrefix: '',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'en',
  },
  {
    code: 'fr',
    localeCode: 'fr',
    label: 'Français',
    default: false,
    textDirection: 'ltr',
    cmsLocale: 'fr',
    iso3LetterCode: 'fra',
    vocabularyLocale: 'fr-FR',
    gbifOrgLocalePrefix: '/fr',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'fr',
  },
  {
    code: 'it',
    localeCode: 'it',
    label: 'Italiano',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'it-IT',
    iso3LetterCode: 'ita',
    gbifOrgLocalePrefix: '/it',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'it',
  },
  {
    code: 'es',
    localeCode: 'es',
    label: 'Español',
    default: false,
    textDirection: 'ltr',
    cmsLocale: 'es',
    vocabularyLocale: 'es-ES',
    iso3LetterCode: 'spa',
    gbifOrgLocalePrefix: '/es',
    grSciCollLocalePrefix: '/es',
    mapTileLocale: 'es',
  },
  {
    code: 'de',
    localeCode: 'de',
    label: 'Deutsch',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'de-DE',
    iso3LetterCode: 'deu',
    vocabularyLocale: 'de-DE',
    gbifOrgLocalePrefix: '',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'de',
  },
  {
    code: 'ar',
    localeCode: 'ar',
    label: 'العربية',
    default: false,
    textDirection: 'rtl',
    reactIntlLocale: 'ar-SA',
    iso3LetterCode: 'ara',
    gbifOrgLocalePrefix: '/ar',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'ar',
  },
  {
    code: 'zh',
    localeCode: 'zh',
    label: '简体中文',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'zh-CN',
    iso3LetterCode: 'zho',
    cmsLocale: 'zh',
    vocabularyLocale: 'zh-CN',
    gbifOrgLocalePrefix: '/zh',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'zh',
  },
  {
    code: 'zh-tw',
    localeCode: 'zh-tw',
    label: '繁體中文',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'zh-TW',
    cmsLocale: 'zh-TW',
    vocabularyLocale: 'zh-TW',
    iso3LetterCode: 'zho',
    gbifOrgLocalePrefix: '/zh-tw',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'zh',
  },
  {
    code: 'ru',
    localeCode: 'ru',
    label: 'Русский',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'ru-RU',
    cmsLocale: 'ru',
    vocabularyLocale: 'ru-RU',
    iso3LetterCode: 'rus',
    gbifOrgLocalePrefix: '/ru',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'ru',
  },
  {
    code: 'cs',
    localeCode: 'cs',
    label: 'Čeština',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'cs-CZ',
    cmsLocale: 'cs',
    vocabularyLocale: 'cs-CZ',
    iso3LetterCode: 'ces',
    gbifOrgLocalePrefix: '',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'cs',
  },
  {
    code: 'ja',
    localeCode: 'ja',
    label: '日本語',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'ja-JP',
    cmsLocale: 'ja',
    vocabularyLocale: 'ja-JP',
    iso3LetterCode: 'jpn',
    gbifOrgLocalePrefix: '/ja',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'ja',
  },
  {
    code: 'pl',
    localeCode: 'pl',
    label: 'Polski',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'pl-PL',
    cmsLocale: 'pl',
    vocabularyLocale: 'pl-PL',
    iso3LetterCode: 'pol',
    gbifOrgLocalePrefix: '',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'pl',
  },
  {
    code: 'pt',
    localeCode: 'pt',
    label: 'Português',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'pt-PT',
    cmsLocale: 'pt',
    vocabularyLocale: 'pt-PT',
    iso3LetterCode: 'por',
    gbifOrgLocalePrefix: '/pt',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'pt',
  },
  {
    code: 'uk',
    localeCode: 'uk',
    label: 'Українська',
    default: false,
    textDirection: 'ltr',
    reactIntlLocale: 'uk-UA',
    cmsLocale: 'uk',
    vocabularyLocale: 'uk-UA',
    iso3LetterCode: 'ukr',
    gbifOrgLocalePrefix: '',
    grSciCollLocalePrefix: '',
    mapTileLocale: 'uk',
  },
];

const enabledLocales = import.meta.env.PUBLIC_ENABLED_LANGUAGES.split(',');
export const languagesOptions = enabledLocales
  .map((code: string) => languageOptions.find((l) => l.code === code))
  .filter(Boolean) as LanguageOption[];
