apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 5
  sauceignore: .sauceignore
cypress:
  configFile: cypress.config.ts
  version: 13.13.1
  record: false
  key: ''
  reporters: []
suites:
  - name: cypress - Windows 10 - chrome
    browser: chrome
    platformName: Windows 10
    config:
      testingType: e2e
      specPattern:
        - 'cypress/e2e/basicTests/*.cy.js'
rootDir: .
artifacts:
  download:
    match:
      - '*'
    when: fail
    directory: ./artifacts
# Specefiy packages used during the tests
npm:
  dependencies:
    - vite
