apiVersion: v1
kind: cypress
defaults: {}
showConsoleLog: false
sauce:
  region: us-west-1
  concurrency: 5
  sauceignore: .sauceignore
  visibility: private
cypress:
  configFile: cypress.config.ts
  version: 15.5.0
  record: false
  key: ''
suites:
  - name: cypress - Windows 10 - chrome
    browser: chrome
    platformName: Windows 10
    config:
      testingType: e2e
      specPattern:
        - 'cypress/e2e/basicTests/*.cy.js'
rootDir: .
artifacts:
  download:
    match:
      - '*'
    when: fail
    directory: ./artifacts
# Specefiy packages used during the tests
npm:
  registry: https://registry.npmjs.org
  packages:
    'vite': '^5.4.2'
    'ts-deepmerge': '^7.0.1'
    '@vitejs/plugin-react': '^4.0.0'
    'vite-plugin-node-polyfills': '^0.22.0'
