const _ = require('lodash');

const whitelist = [
  // 'all',
  // 'amplificationItems',
  // 'australiaSpatialLayers',
  'basisOfRecord',
  'catalogNumber',
  'collectionCode',
  'collectionKey',
  'continent',
  'coordinatePrecision',
  'coordinateUncertaintyInMeters',
  'coordinates',
  'country',
  'countryCode',
  'crawlId',
  'created',
  'datasetKey',
  'datasetPublishingCountry',
  'datasetTitle',
  'dateIdentified',
  'day',
  'decimalLatitude',
  'decimalLongitude',
  'depth',
  'depthAccuracy',
  'elevation',
  'elevationAccuracy',
  'endDayOfYear',
  'endorsingNodeKey',
  'establishmentMeans',
  'eventDate',
  'eventDateSingle',
  'eventId',
  'gbifClassification',
  'gbifId',
  // 'hasCoordinate',
  // 'hasGeospatialIssue',
  'id',
  'identifiedBy',
  'identifiedByIds',
  'individualCount',
  'installationKey',
  'institutionCode',
  'institutionKey',
  'issues',
  'lastCrawled',
  'license',
  'lifeStage',
  'locality',
  'maximumDepthInMeters',
  'maximumDistanceAboveSurfaceInMeters',
  'maximumElevationInMeters',
  'measurementOrFactItems',
  'mediaLicenses',
  'mediaTypes',
  'minimumDepthInMeters',
  'minimumDistanceAboveSurfaceInMeters',
  'minimumElevationInMeters',
  'modified',
  'month',
  'multimediaItems',
  'networkKeys',
  // 'notIssues',
  'occurrenceId',
  'occurrenceStatus',
  'organismId',
  'organismQuantity',
  'organismQuantityType',
  'parentEventId',
  'programmeAcronym',
  'projectId',
  'protocol',
  'publisherTitle',
  'publishingCountry',
  'publishingOrganizationKey',
  'recordNumber',
  'recordedBy',
  'recordedByIds',
  'references',
  'relativeOrganismQuantity',
  'repatriated',
  'sampleSizeUnit',
  'sampleSizeValue',
  'samplingProtocol',
  'scoordinates',
  'sex',
  'startDayOfYear',
  'stateProvince',
  'typeStatus',
  'typifiedName',
  'verbatim',
  'waterBody',
  'year'
];

function reduce(item) {
  return _.pick(item._source, whitelist)
}

module.exports = {
  reduce
}