export default [
  'locality',
  'samplingProtocol',
  'measurementOrFactTypes',
  'stateProvince',
  'datasetKey',
  'eventTypeHierarchy',
  'eventTypeHierarchyJoined',
  'eventHierarchy',
  'eventHierarchyJoined',
  'measurementOrFactTypes',
  'locationID',
  'year',
  'month',
  'eventType',
  'scientificNames',
  'surveyID',
];
