export const filters = [
  'country',
  'publishingCountryCode',
  'datasetKey',
  'publisherKey',
  'institutionCode',
  'catalogNumber',
  'hostingOrganizationKey',
  'year',
  'basisOfRecord',
  'typeStatus',
  'occurrenceIssue',
  'mediaType',
  'license',
  'coordinateUncertainty',
  'depth',
  'organismQuantity',
  'sampleSizeUnit',
  'sampleSizeValue',
  'relativeOrganismQuantity',
  'month',
  'continent',
  'protocol',
  'establishmentMeans',
  'recordedBy',
  'recordNumber',
  'recordedById',
  'identifiedById',
  'locality',
  'waterBody',
  'stateProvince',
  'eventId',
  'parentEventId',
  'samplingProtocol',
  'elevation',
  'gadmGid',
  'identifiedBy',
  'q',
  'dwcaExtension'
].sort();

const highlighted = [
  'eventId',
  'parentEventId',
  'samplingProtocol',
  'year',
  'country',
];

export default { filters, included: filters, highlighted };