export default [
  'publisher',
  'year',
  'topics',
  'peerReview',
  'openAccess',
  'source',
  'literatureType',
  'relevance',
  'countriesOfCoverage',
  'countriesOfResearcher',
  'publishingOrganizationKey',
  'gbifDatasetKey',
  'gbifNetworkKey',
  'gbifProgrammeAcronym',
];
